baseURL = "https://atorizva.github.io"
theme = "ficurinia"
title = 'DataType'
languageCode = 'es'
defaultContentLanguage = "es"
copyright = "Alfonso Toriz Vazquez. [CC BY-SA 4.0](https://creativecommons.org/licenses/by/4.0/)."

[languages]
    [languages.en]
        languageName = "English"
        weight = 1
        contentDir = "content/en"
    [languages.es]
        languageName = "Español"
        weight = 2
        contentDir = "content/es"


summaryLength = 70  # number of words for article summaries

[pagination]
    pagerSize = 5  # number of articles per page in the index


[params]
    author = "Alfonso Toriz Vazquez"
    email = "alfonso.toriz@tutanota.com"
    website = "https://atorizva.github.io"
    avatar = "/apple-touch-icon.png"

    posts ="posts"
    showPostsLink = true
    
    enableShareOnFediverse = true # enable a button at the end of an article to share it on the fediverse
    fediverseAccount = "@atorizva@masto.es"
    
    logo = "/logo.svg"
    logoAltText = "Logo"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    svgicon = "/logo.svg"

[menu]
    # these links will be added to the main navigation menu, sorted by weight
    # other elements in this menu are added automatically from the "pages" folder
    # the folder it will look into can be customized with the pages variable
    # in params above
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    # these links (menu.icons) will be added as icon links below the main nav
    [[menu.icons]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/atorizva"
        weight = 40
    [[menu.icons]]
        identifier = "mastodon"
        name = "Mastodon"
        url = "https://masto.es/@atorizva"
        weight = 30
    [[menu.icons]]
        identifier = "bluesky"
        name = "Bluesky"
        url = "https://bsky.app/profile/atorizva.bsky.social"
        weight = 20
    [[menu.icons]]
        identifier = "email"
        name = "Email"
        url = "mailto:alfonso.toriz@.org"
        weight = 10
