baseURL = "https://atorizva.github.io"
theme = "nostyleplease"
title = 'DataType'
languageCode = 'es'
defaultContentLanguage = "es"

[params]
    author = "Alfonso Toriz Vazquez"
    email = "alfonso.toriz@tutanota.com"
    website = "https://atorizva.github.io"
    favicon = "favicon.svg" # path to the favicon, relative to the "static" folder

    posts ="posts"
    showPostsLink = true
    
    enableShareOnFediverse = true # enable a button at the end of an article to share it on the fediverse
    fediverseAccount = "@atorizva@masto.es"

    [params.theme_config]
        show_description = true
        appearance = "light"
        back_home_text = "cd .."
        date_format = "02 Jan 2006"

[languages]
    [languages.en]
        languageName = "English"
        weight = 1
        contentDir = "content/en"
    [languages.es]
        languageName = "Español"
        weight = 2
        contentDir = "content/es"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']

[pagination]
    pagerSize = 5  # number of articles per page in the index

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
                title = true

    [markup.highlight]
        anchorLineNos      = false 
        codeFences         = true 
        guessSyntax        = false
        hl_Lines           = ''
        hl_inline          = false 
        lineAnchors        = ''
        lineNoStart        = 1
        lineNos            = true
        lineNumbersInTable = false 
        noClasses          = true
        noHl               = false
        style              = 'gruvbox-light' 
        tabWidth           = 4

    [markup.tableOfContents]
        startLevel = 2
        endLevel   = 3
        ordered    = false



[menu]
    # these links will be added to the main navigation menu, sorted by weight
    # other elements in this menu are added automatically from the "pages" folder
    # the folder it will look into can be customized with the pages variable
    # in params above
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    # these links (menu.icons) will be added as icon links below the main nav
    [[menu.icons]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/atorizva"
        weight = 40
    [[menu.icons]]
        identifier = "mastodon"
        name = "Mastodon"
        url = "https://masto.es/@atorizva"
        weight = 30
    [[menu.icons]]
        identifier = "bluesky"
        name = "Bluesky"
        url = "https://bsky.app/profile/atorizva.bsky.social"
        weight = 20
    [[menu.icons]]
        identifier = "email"
        name = "Email"
        url = "mailto:alfonso.toriz@.org"
        weight = 10
